version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env 
    depends_on:
      - mongo
    networks:
      - chat-app

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-app
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - NODE_ENV=production
    ports:
      - "5173:5173"  
    depends_on:
      - backend
    networks:
      - chat-app

volumes:
  mongo-data:

networks:
  chat-app:
    driver: bridge

